### PR TITLE
added support for multiple channels

### PR DESCRIPTION
**Pull request by m-sch**
this version comes with a json file in the app bundle storing all the
m3u streams
providing streams of tv channels from some countries will be coming in
future versions

### CODE REVIEW

**Comment by kane2931** [comment]
Good job man.

It will be more "future proof" if the json file was hosted somewhere online not in the bundle itself.
ex: https://gist.githubusercontent.com/kane2931/fd410b69b8942a1d2b92/raw/a403accf158fbc9dbf1a19caace73addb50090ce/gistfile1.txt

So adding and removing channels will be more easy then modify and rebuld the code and re-sideload the app on the Apple TV.

**Comment by m-sch** [comment]
Just made this for my own usage. I'll host it online via gist and resend a pull request if necessary?

**Comment by kane2931** [comment]
I've made some experiments with gist and everytime you update the file, the "raw" url change, so gist will not be that good for updating.  Maybe Pastebin will work better ??  I'm pretty to new to programming, i don't understand how github works for pulling request and everything. Sorry.

**Comment by m-sch** [comment]
It's not that hard to learn
https://help.github.com/articles/merging-a-pull-request/

**Pull request closed without merging**
